import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(__dirname, "../dist/index.html"), "utf8");
const kb = (html.length / 1024).toFixed(0);

const output = [
  "// Generated by editor-web build — do not edit manually.",
  "// Run `bun run build:editor` from the project root to regenerate.",
  `export const MILKDOWN_EDITOR_HTML = ${JSON.stringify(html)};`,
  "",
].join("\n");

writeFileSync(join(__dirname, "../../assets/milkdown-editor.ts"), output);
console.log(`Generated assets/milkdown-editor.ts (${kb}KB)`);
